import Link from "next/link";
import Navbar from "./Navbar";
import Footer from "./Footer";

export type PageSpec = { label: string; title: string; lead: string; tone: "violet" | "cyan" | "amber" | "rose" | "emerald" | "slate"; mode: "signal" | "editorial" | "culture" | "library" | "terminal"; items: string[] };
const tone = { violet: ["from-violet-950 via-indigo-900 to-slate-950", "bg-violet-600", "bg-violet-50"], cyan: ["from-cyan-950 via-slate-900 to-blue-950", "bg-cyan-600", "bg-cyan-50"], amber: ["from-amber-950 via-orange-900 to-slate-950", "bg-amber-500", "bg-amber-50"], rose: ["from-rose-950 via-fuchsia-900 to-slate-950", "bg-rose-600", "bg-rose-50"], emerald: ["from-emerald-950 via-teal-900 to-slate-950", "bg-emerald-600", "bg-emerald-50"], slate: ["from-slate-950 via-slate-800 to-indigo-950", "bg-slate-800", "bg-slate-100"] } as const;

export default function PageCanvas({ spec }: { spec: PageSpec }) {
 const [hero, solid, soft] = tone[spec.tone]; const editorial = spec.mode === "editorial" || spec.mode === "library"; const culture = spec.mode === "culture";
 return <main className="min-h-screen bg-[#fcfdff] text-slate-900"><Navbar />
  <section className={`relative overflow-hidden bg-gradient-to-br ${hero} px-6 py-24 text-white md:px-12 md:py-32`}><div className="absolute -right-20 -top-12 h-80 w-80 rounded-full border-[28px] border-white/10" /><div className="relative mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[.25em] text-white/60">{spec.label}</p><div className={editorial ? "mt-8 max-w-4xl" : "mt-8 grid gap-10 lg:grid-cols-[1.3fr_.7fr] lg:items-end"}><div><h1 className="text-5xl font-black leading-[.96] tracking-tight md:text-7xl">{spec.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-200">{spec.lead}</p><Link href="/contact" className="mt-8 inline-block rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-900">Start a conversation →</Link></div>{!editorial && <div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-5 backdrop-blur"><b className="text-3xl">01</b><p className="mt-7 text-xs text-slate-300">Clearer direction</p></div><div className="mt-8 rounded-2xl bg-white/10 p-5 backdrop-blur"><b className="text-3xl">02</b><p className="mt-7 text-xs text-slate-300">Stronger outcomes</p></div></div>}</div></div></section>
  <section className="border-b border-slate-100 bg-white px-6 py-6 md:px-12"><div className="mx-auto flex max-w-6xl justify-between gap-5 text-xs font-black uppercase tracking-[.16em] text-slate-400"><span>Strategy</span><span>Execution</span><span>Momentum</span></div></section>
  <section className="px-6 py-24 md:px-12"><div className="mx-auto max-w-6xl"><p className={`text-xs font-black uppercase tracking-[.2em] ${spec.tone === "amber" ? "text-amber-600" : "text-indigo-600"}`}>01 — The opportunity</p><div className={culture ? "mt-6 grid gap-10 md:grid-cols-[.8fr_1.2fr]" : "mt-6 grid gap-10 md:grid-cols-2"}><h2 className="text-4xl font-black leading-tight md:text-5xl">Work that feels more intentional.</h2><p className="text-lg leading-8 text-slate-500">We bring a useful point of view, a practical operating system, and an appetite for better answers—not more noise.</p></div></div></section>
  <section className={`${soft} px-6 py-20 md:px-12`}><div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[.2em] text-slate-500">02 — The essentials</p><div className={editorial ? "mt-8 grid gap-4 md:grid-cols-2" : "mt-8 grid gap-4 md:grid-cols-4"}>{spec.items.slice(0, 4).map((item, i) => <article key={item} className={`min-h-44 rounded-3xl bg-white p-6 ${i === 0 && culture ? "md:col-span-2" : ""}`}><span className={`inline-flex h-9 w-9 items-center justify-center rounded-xl ${soft} text-xs font-black`}>0{i + 1}</span><h3 className="mt-7 text-xl font-black">{item}</h3><p className="mt-2 text-sm leading-6 text-slate-500">A focused capability designed to create real forward movement.</p></article>)}</div></div></section>
  <section className="bg-white px-6 py-24 md:px-12"><div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[.2em] text-indigo-600">03 — The process</p><div className="mt-10 grid gap-5 md:grid-cols-3">{["Understand", "Activate", "Improve"].map((x,i) => <div key={x} className="border-t-2 border-slate-900 pt-5"><p className="text-xs font-black text-slate-400">0{i+1}</p><h3 className="mt-8 text-2xl font-black">{x}</h3><p className="mt-3 text-sm leading-6 text-slate-500">Simple stages, shared visibility, and a clear reason for every next move.</p></div>)}</div></div></section>
  <section className="px-6 py-20 md:px-12"><div className={`mx-auto grid max-w-6xl gap-5 ${editorial ? "md:grid-cols-[.8fr_1.2fr]" : "md:grid-cols-2"}`}><div className={`rounded-[32px] ${solid} p-9 text-white`}><p className="text-xs font-black uppercase tracking-[.2em] text-white/65">04 — A better view</p><h2 className="mt-16 text-4xl font-black leading-tight">The details should lead somewhere.</h2></div><div className="rounded-[32px] bg-slate-950 p-9 text-white"><p className="text-xs font-black uppercase tracking-[.2em] text-white/50">In practice</p><div className="mt-12 space-y-5">{spec.items.slice(4, 7).map((item) => <p key={item} className="border-b border-white/15 pb-4 text-lg font-bold">{item} <span className="float-right text-white/40">↗</span></p>)}</div></div></div></section>
  <section className="bg-white px-6 py-24 md:px-12"><div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[.2em] text-indigo-600">05 — Built around you</p><h2 className="mt-4 max-w-2xl text-4xl font-black md:text-5xl">A flexible model for the way your team works.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{["Start focused", "See the signal", "Scale with intent"].map((x) => <div key={x} className="rounded-2xl border border-slate-100 p-6"><h3 className="text-lg font-black">{x}</h3><p className="mt-3 text-sm leading-6 text-slate-500">A clear, collaborative experience from first conversation through every next phase.</p></div>)}</div></div></section>
  <section className={`${soft} px-6 py-20 md:px-12`}><div className="mx-auto max-w-6xl text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-slate-500">06 — The proof</p><blockquote className="mx-auto mt-7 max-w-4xl text-3xl font-black leading-tight md:text-5xl">“The best partnerships make ambitious work feel possible.”</blockquote><p className="mt-6 text-sm font-bold text-slate-500">A shared standard for every project</p></div></section>
  <section className="bg-white px-6 py-20 md:px-12"><div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[.2em] text-indigo-600">07 — Questions, answered</p><div className="mt-8 grid gap-3 md:grid-cols-2">{["Where do we begin?", "How will we work together?", "What does success look like?", "Who will support us?"].map(q => <div key={q} className="flex justify-between rounded-xl border border-slate-100 p-5 font-bold">{q}<span className="text-slate-400">+</span></div>)}</div></div></section>
  <section className={`bg-gradient-to-r ${hero} px-6 py-24 text-center text-white md:px-12`}><p className="text-xs font-black uppercase tracking-[.2em] text-white/60">08 — Your next move</p><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-black md:text-6xl">Let’s make the next chapter count.</h2><Link href="/contact" className="mt-8 inline-block rounded-xl bg-white px-6 py-3 text-sm font-bold text-slate-900">Talk to our team →</Link></section>
  <Footer />
 </main>;
}
